spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demodb
    username: demodb
    password: password

  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

passkeys-api:
  uri: http://localhost:8080/
  # used in resources/templates/fragment-footer.html
  app-id: 2874b5d1-c708-4d5b-87ad-06b1856e06db
  api-key: 952f3cb0c228fbc73c6ec7e14564a762

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081