spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demodb
    password: password
  jpa:
    hibernate:
      ddl-auto: update

relyingparty:
  display-name: LocalHost
  hostname: localhost
  allow-origin-port: false
